// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFj1zvxdpe0UbYZAknirXdvTi8JlztcZc',
    appId: '1:211503279151:web:3fa62f7301153b61b3eada',
    messagingSenderId: '211503279151',
    projectId: 'schoolconnect-rishi-2026',
    authDomain: 'schoolconnect-rishi-2026.firebaseapp.com',
    storageBucket: 'schoolconnect-rishi-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALLzn01xpeHTuidjFK-akviu0grImOlK4',
    appId: '1:211503279151:android:1dee3d3b5427ed53b3eada',
    messagingSenderId: '211503279151',
    projectId: 'schoolconnect-rishi-2026',
    storageBucket: 'schoolconnect-rishi-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw-_8EpAD20B9nH6lwTV_0QS_ouZ47e7s',
    appId: '1:211503279151:ios:778efe431456594cb3eada',
    messagingSenderId: '211503279151',
    projectId: 'schoolconnect-rishi-2026',
    storageBucket: 'schoolconnect-rishi-2026.firebasestorage.app',
    iosBundleId: 'com.example.schoolConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw-_8EpAD20B9nH6lwTV_0QS_ouZ47e7s',
    appId: '1:211503279151:ios:778efe431456594cb3eada',
    messagingSenderId: '211503279151',
    projectId: 'schoolconnect-rishi-2026',
    storageBucket: 'schoolconnect-rishi-2026.firebasestorage.app',
    iosBundleId: 'com.example.schoolConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFj1zvxdpe0UbYZAknirXdvTi8JlztcZc',
    appId: '1:211503279151:web:b6c31f706384dd80b3eada',
    messagingSenderId: '211503279151',
    projectId: 'schoolconnect-rishi-2026',
    authDomain: 'schoolconnect-rishi-2026.firebaseapp.com',
    storageBucket: 'schoolconnect-rishi-2026.firebasestorage.app',
  );
}
